server:
  port: 8071

#jdbc
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/boot_gmall_study?characterEncoding=UTF-8
    username: root
    password: JXsy930628
  redis:
    host: 192.168.101.20
    port: 6379
    database: 0


mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/mapper/*Mapper.xml

#dubbo
dubbo:
  application:
    name: manager-service
  protocol:
    name: dubbo
  #注册中心
  registry:
    address: 192.168.101.20:2181
    protocol: zookeeper
  #包扫描
  scan:
    base-packages: com.jarvis.gmall

#日志级别
logging:
  level:
    root: info
