server:
  port: 8000

#jdbc
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/boot_gmall_study?characterEncoding=UTF-8
    username: root
    password: JXsy930628
  redis:
    host: 192.168.101.20
    port: 6379
    database: 0


mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/mapper/*Mapper.xml
